module.exports = {
  dishes: [
    "黄焖鸡米饭",
    "馄饨",
    "炒面",
    "沙县小吃",
    "烤肉",
    "咖喱",
    "花甲",
    "肯德基",
    "必胜客",
    "盖浇饭",
    "卤肉饭",
    "米线",
    "披萨",
    "日料",
    "火锅",
    "烧烤",
    "蛋糕",
    "韩国菜",
    "川菜",
    "江浙菜",
    "麦当劳",
    "小龙虾"
  ],
  dishesObjects:[
    {
      "name": "黄焖鸡米饭",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "馄饨",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "炒面",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "烤肉",
      "level": 2,
      "min": 2,
      "max": 6,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "咖喱",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "花甲",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "肯德基",
      "level": 2,
      "min": 1,
      "max": 4,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "必胜客",
      "level": 2,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "盖浇饭",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "卤肉饭",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "米线",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "披萨",
      "level": 2,
      "min": 2,
      "max": 6,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "日料",
      "level": 2,
      "min": 2,
      "max": 6,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "火锅",
      "level": 2,
      "min": 2,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "烧烤",
      "level": 2,
      "min": 1,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "蛋糕",
      "level": 2,
      "min": 1,
      "max": 8,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "韩国菜",
      "level": 2,
      "min": 2,
      "max": 6,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "川菜",
      "level": 2,
      "min": 2,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "江浙菜",
      "level": 2,
      "min": 1,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "海鲜",
      "level": 2,
      "min": 2,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": false,
      "on": true
    }, {
      "name": "麦当劳",
      "level": 2,
      "min": 1,
      "max": 6,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "小龙虾",
      "level": 2,
      "min": 1,
      "max": 10,
      "breakfast": false,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "烧饼",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": false,
      "on": true
    }, {
      "name": "油条",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": false,
      "on": true
    }, {
      "name": "小笼包",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": true,
      "on": true
    }, {
      "name": "生煎",
      "level": 1,
      "min": 1,
      "max": 4,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "煎饼",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": true,
      "dinner": true,
      "night": true,
      "on": true
    }, {
      "name": "包子",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": true,
      "on": true
    }, {
      "name": "豆浆",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": true,
      "on": true
    }, {
      "name": "粥",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": true,
      "on": true
    }, {
      "name": "茶叶蛋",
      "level": 1,
      "min": 1,
      "max": 2,
      "breakfast": true,
      "lunch": false,
      "dinner": false,
      "night": true,
      "on": true
    }
  ]
};
